### ISSUE TITLE
Chest Boat - Stored items disappear when the boat is picked up

### ISSUE THREAD

**Issue by Fuzzbling** [team-abnormals/extra-boats#35]
**Version**: extraboats-1.16.5-2.1.0.jar

**Steps to reproduce**:
Make a chest boat, shift+right click to open the chest.
Insert an item (like an Oak sapling).
Pick up the boat by shift+right clicking the front of the boat with empty hands (no primary or off-hand item).
Place the boat back down, put something in your hands and shift-right click the chest again.
Items will be lost.

**Secondary bug**:
Reproduce the steps above, but with a boat of a different wood type (like Spruce for example).
After picking up the boat, it changes to an Oak type, rather than the one it was initially made out of.

**Comment by bageldotjpg** [comment]
...? What are you using to pick-up the boats?

**Comment by Fuzzbling** [comment]
NM, Figured out what was causing it. The CarryOn mod (blacklisted these boat so it's a non-issue now).
